### ISSUE TITLE
gitlab runner should not depend on kubectl being installed and should utilize `uds zarf tools kubectl`

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-package-gitlab-runner#31]
### Environment
Device and OS: m3 max mac
App/package versions: N/A
Kubernetes distro being used: N/A
Other:

### Steps to reproduce
1. try to install gitlab runner from a computer that doesnt have kubectl installed

### Expected result
it works
### Actual Result
it fails
### Visual Proof (screenshots, videos, text, etc)
https://github.com/defenseunicorns/uds-package-gitlab-runner/blob/9025c6bf550361ec7c93b1ec623d8c14a74e2c5b/zarf.yaml#L21
### Additional Context
Kudos to @ericwyles finding this.

**Comment by ericwyles** [comment]
I'm working on this and opened a PR.
