### ISSUE TITLE
Update repo to utilize workflows, actions and tasks from the uds-common repo

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-package-gitlab-runner#38]
### Describe what should be investigated or refactored
We created a repo to enable reuse of common uds tasks, gh actions and gh workflows. This repo should be updated to utilize the common ones where possible. 

### Links to any relevant code
https://github.com/defenseunicorns/uds-common

### Additional context
Any questions just ask.

**Comment by naveensrinivasan** [comment]
@zachariahmiller Can you please expand on which ones? This will help me. Thanks

**Comment by zachariahmiller** [comment]
@naveensrinivasan sure. I think at least using the save-logs and setup action in the common repo and at least the commitlint workflow. Looking at what is in common right now it looks like we might not be in a position to utilize the others without some more iteration in the uds-common repo.

**Comment by zachariahmiller** [comment]
The save logs one in particular has been driving me nuts because it currently causes CI to fail even though it passes. Multiple repos have it without passing an input in to make the name of the artifact unique and then it fails the pipeline because of conflicts. In uds-common the action takes that input so switching to it and passing in the flavor from the matrix in the calling workflow will resolve that issue

**Comment by naveensrinivasan** [comment]
https://github.com/defenseunicorns/uds-package-sonarqube/pull/42

**Comment by zachariahmiller** [comment]
Hey @naveensrinivasan it looks like this was the wrong issue (they are named the same just in each repo) can you please reopen this one and close https://github.com/defenseunicorns/uds-package-sonarqube/issues/40 as completed by the referenced PR?

Sorry for any confusion.

**Comment by naveensrinivasan** [comment]
🤦 Thanks
