### ISSUE TITLE
Diagnose what broke the upstream arm package publish and fix/republish

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-package-gitlab-runner#51]
### Links to any relevant code
(optional) i.e. - https://github.com/defenseunicorns/uds-package-gitlab-runner/blob/main/README.md?plain=1#L1

### Additional context
Add any other context or screenshots about the technical debt here.

**Comment by Racer159** [comment]
Specifically this run: https://github.com/defenseunicorns/uds-package-gitlab-runner/actions/runs/8182582247/job/22374144274
